apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-services-deployment
  labels:
    app: docker-k8s-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app : docker-k8s-services
  template:
    metadata :
      labels:
        app: docker-k8s-services
    spec:
      containers:
      - name: docker-k8s-services
        image: helitha26/services-iit
        ports:
        - containerPort: 8082

